_game_name = "Tower Game"
_game_side_pannel = 300
_screen_width = 1000
_screen_height = 800
_font_famalie = "Orbitron"
_font_size_header = 20
_font_size_mid = 18
_font_size_text = 16
_UI_margin = 30
_UI_margin_y = 40
_game_difficulty = 2
